import Head from "next/head";

import { Card, Calendar } from "antd";

export default function Game() {
  const onChange = (value, mode) => {
    console.log(value.format("YYYY-MM-DD"), mode);
    fetch(`/api/schedule?date=${value.format("YYYY-MM-DD")}`)
    .then(response=>response.json())
    .then(data=>console.log(data));
  };

  const cardStyle = {
    width: "400px",
    border: "1px solid #f0f0f0",
    borderRadius: "2px",
  };

  return (
    <div>
      <Head>
        <title>Game</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Game Today</h1>
        <Card style={cardStyle}>
          <Calendar
            fullscreen={false}
            onPanelChange={onChange}
            onSelect={onChange}
          />
        </Card>
      </main>
    </div>
  );
}
